### ISSUE TITLE
pydot/1.4.1: FAIL: test_graphviz_regression_tests (__main__.TestGraphAPI)

### ISSUE THREAD

**Issue by sandrotosi** [pydot/pydot#204]
Hello,
when running tests for pydot 1.4.1 on Debian, we got this test failure:

python2.7:
```
======================================================================
FAIL: test_graphviz_regression_tests (__main__.TestGraphAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/pydot_unittest.py", line 210, in test_graphviz_regression_tests
    self._render_and_compare_dot_files(path)
  File "test/pydot_unittest.py", line 230, in _render_and_compare_dot_files
    assert pydot_sha == graphviz_sha, (pydot_sha, graphviz_sha)
AssertionError: ('e9bb2c841150a6731b1bdf0d01422577f72747c6b4644c7448a0701362ab620dd7d1756fb288e422e6442a8d7ec6aa79197e29a518230b921b24d37be3a53636', '836c766bc6821932eb44123938f727ec3a46cf2c66a31921b9b31b4f09536e78')

----------------------------------------------------------------------
```

python3.7:
```
======================================================================
FAIL: test_graphviz_regression_tests (__main__.TestGraphAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/pydot_unittest.py", line 210, in test_graphviz_regression_tests
    self._render_and_compare_dot_files(path)
  File "test/pydot_unittest.py", line 230, in _render_and_compare_dot_files
    assert pydot_sha == graphviz_sha, (pydot_sha, graphviz_sha)
AssertionError: ('e9bb2c841150a6731b1bdf0d01422577f72747c6b4644c7448a0701362ab620dd7d1756fb288e422e6442a8d7ec6aa79197e29a518230b921b24d37be3a53636', '836c766bc6821932eb44123938f727ec3a46cf2c66a31921b9b31b4f09536e78')

----------------------------------------------------------------------
```

**Comment by felixonmars** [comment]
Same error here with Python 3.7, with different sha though:

```
======================================================================
FAIL: test_graphviz_regression_tests (__main__.TestGraphAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pydot_unittest.py", line 210, in test_graphviz_regression_tests
    self._render_and_compare_dot_files(path)
  File "pydot_unittest.py", line 230, in _render_and_compare_dot_files
    assert pydot_sha == graphviz_sha, (pydot_sha, graphviz_sha)
AssertionError: ('b9eb7a95f50ca609d6798845f258fc3a45af3c26a24d2906875790fcee4b2f20091556a3fed78b2433e6b032ab41d5e48f8f1999db4945348d7720b7b3a21083', '18ae393aff762592aec9592c7c786bef8da35bbf3e94ea60e7e5d48f12621350')
```

**Comment by peternowee** [comment]
I ran into this error as well. PR #211 solves it for me, please check it out.

**Comment by peternowee** [comment]
@sandrotosi @felixonmars Thanks for reporting. @prmtl has granted me write access to this repository and I hope we can get a first point release (1.4.2) out soon for the most obvious fixes, like this one.
