### ISSUE TITLE
Validation of HTML strings and HTML-like labels, or lack thereof

### ISSUE THREAD

**Issue by peternowee** [pydot/pydot#215]
### Introduction
Currently, pydot does not validate HTML(-like) strings or HTML(-like) labels, as defined by The DOT Language. I am opening this issue not expecting an immediate change in that, but rather to have a central place for discussion and tracking related issues, more specifically:

- To document the lack of validation and the reasons behind it,
- To link to specific issues that were caused or aggravated by the lack of validation,
- To discuss mitigations, workarounds, documentation and partial or, who knows one day, complete implementations of validation,
- To share other findings or opinions related to these subjects.

### Definitions
To aid in discussion, we should try to use the same terms. Here is a first suggestion, feel free to suggest improvements:

- HTML string or HTML-like string: As defined by [the DOT language](https://www.Graphviz.org/doc/info/lang.html). Note that there it says that HTML strings must be legal XML, so "HTML string" may be somewhat of a misnomer, but it is used throughout the DOT and Graphviz documentation, so I will follow that.
- HTML label or HTML-like label: An HTML string used as a label attribute in certain contexts, as defined by [the DOT language](https://www.Graphviz.org/doc/info/lang.html) and the document [Node Shapes: HTML-Like Labels](https://www.Graphviz.org/doc/info/shapes.html#html). Besides being legal XML, they must also follow the syntax defined in that last document. Again, "HTML label" is a misnomer, because the syntax is described as "modeled on HTML", but "not really HTML". For example, it does not support all of HTML (e.g. `<P>` is not supported), and adds its own attributes (without the `data-` prefix that would allow for that in HTML5), such as `<TABLE PORT="portName">`.
- True HTML or real HTML: The normal (outside the DOT/Graphviz world) definition of HTML. Use adjectives like "true" or "real" to clearly distinguish it from the DOT-specific terms defined above.

### Examples
Here are three minimal working examples, followed by a summary and a link to two real world examples. 

Used versions: python 2.7.16 and 3.7.3, pydot 1.4.1, chardet 3.0.4, pip 19.2.3, pyparsing 2.4.2, setuptools 41.2.0, wheel 0.33.6, Debian 10.1 (buster), Graphviz 2.40.1-6.

#### Example 1: Invalid XML in an HTML string
```
import pydot

G = pydot.Dot()
G.add_node(pydot.Node('N', **{'<<test test>': '""'}))
print(G.to_string())
G.write_dot('broken_html_ID.dot', prog=['dot'])
```
Output of `G.to_string()`:
```
digraph G {
N [<<test test>=""];
}
```
Output of `G.write_dot()`:
```
"dot" with args ['-Tdot', '/tmp/tmpUiJgrg'] returned code: 1

stdout, stderr:
 
Error: /tmp/tmpUiJgrg: syntax error in line 4 scanning a HTML string (missing '>'? bad nesting? longer than 16384?)
String starting:<<test test>=""];
}

Traceback (most recent call last):
  File "broken_html_string_ID.py", line 7, in <module>
    G.write_dot('broken_html_ID.dot', prog=['dot'])
  File "pydot.py", line 1734, in new_method
    encoding=encoding)
  File "pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "pydot.py", line 1947, in create
    assert process.returncode == 0, process.returncode
AssertionError: 1
```
#### Example 2: Invalid XML in an HTML label
```
import pydot

G = pydot.Dot()
G.add_node(pydot.Node('N', **{'label': '<<b>test>'}))
print(G.to_string())
G.write_dot('broken_html_label_closing_tag.dot', prog=['dot'])
```
Output of `G.to_string()`:
```
digraph G {
N [label=<<b>test>];
}
```
Output of `G.write_dot()`:
```
"dot" with args ['-Tdot', '/tmp/tmpWXjQWa'] returned code: 1

stdout, stderr:
 digraph G {
	graph [bb="0,0,54,36"];
	node [label="\N"];
	N	 [height=0.5,
		label=<<b>test>,
		pos="27,18",
		width=0.75];
}

Error: mismatched tag in line 1 
... test</HTML> ...
in label of node N

Traceback (most recent call last):
[...]
  File "pydot.py", line 1947, in create
    assert process.returncode == 0, process.returncode
AssertionError: 1
```
#### Example 3: Valid true HTML, valid XML, but invalid DOT HTML label
The paragraph tag (`<p>` or `<P>`) is not included in the DOT definition of HTML-like labels.
```
import pydot

G = pydot.Dot()
G.add_node(pydot.Node('N', **{'label': '<<p>test</p>>'}))
print(G.to_string())
G.write_dot('broken_html_label_p_tag.dot', prog=['dot'])
```
Output of `G.to_string()`:
```
digraph G {
N [label=<<p>test</p>>];
}
```
Output of `G.write_dot()`:
```
"dot" with args ['-Tdot', '/tmp/tmp3Y6fk4'] returned code: 1

stdout, stderr:
 digraph G {
	graph [bb="0,0,54,36"];
	node [label="\N"];
	N	 [height=0.5,
		label=<<p>test</p>>,
		pos="27,18",
		width=0.75];
}

Error: Unknown HTML element <p> on line 1 
in label of node N

Traceback (most recent call last):
[...]
  File "pydot.py", line 1947, in create
    assert process.returncode == 0, process.returncode
AssertionError: 1
```
#### Summary of examples 1, 2 and 3

All three examples show that:
- pydot allows adding invalid HTML strings and HTML labels to a node.
- pydot will write DOT strings containing invalid HTML strings and HTML labels, which I believe makes those DOT strings invalid in their entirety as well.
- Graphviz then complains about the broken HTML by emitting an error message and returning a non-zero exit code (here: 1).
- After receiving the non-zero exit code from Graphviz, pydot raises an AssertionError.

Examples 2 and 3 also show that:
- Graphviz is somewhat tolerant of some invalid HTML strings or labels. In that case, it will still print an error message and return a non-zero exit code, but return data on stdout as well. In case of DOT output, it will contain the invalid HTML again. (Not shown in the examples, but in case image output was requested, Graphviz would write a readable image to stdout.)
- However, pydot ignores the Graphviz output on stdout in these cases, because Graphviz returned a non-zero exit code.

#### Real world examples

The lack of validation by pydot means that only at the very end, when receiving back the results for the entire graph from Graphviz, an error can be reported. Since many Graphviz errors share the same exit code (`1`), pydot cannot do much more than pass on the Graphviz error message. But in practice, with large graphs containing many HTML strings, the Graphviz error message will not be as clear as the ones shown in the minimal examples above. With such a late and unclear error message, it is difficult for the user to trace back what went wrong exactly. Two examples of this, from two different users, can be found in issue pydot/pydot#203 (Problem with graph.write.png...AssertionError: 1).

**Comment by peternowee** [comment]
### Other findings

- For comparison, I had a look at the [Graphviz C libraries](https://www.graphviz.org/documentation/) that come with Graphviz itself. Unless I am missing something, it looks like they also do not do any validation of HTML during graph construction, neither at the time an HTML-like string is added to storage using `agstrdup_html()`, nor later when the label-attribute of a node is set through `agsafeset()`. Only at very end, when layout of the entire graph is requested by calling `gvLayout()`, will errors be returned. This is comparable to the current behavior of pydot (1.4.1). See attachment [graphviz-html-test.c](https://github.com/pydot/pydot/files/3665634/graphviz-html-test.c.txt) for example code. 

- I also checked if Graphviz provides a specialized validation component to possibly use:
  - No: The Graphviz manual page (`man 7 graphviz`) lists all the executables with short descriptions. [`gvpr`](https://graphviz.gitlab.io/_pages/pdf/gvpr.1.pdf) came close, because it has a function `ishtml()`. However, the outcome of that function is merely determined by the so-called HTML bit, which seems to be set if the string was wrapped in angle brackets (ishtml: true) instead of double quotes (ishtml: false). I did not see any sign of actual validation. `gvpr` does fail with the exactly the same error as other Graphviz executables (e.g. `dot`) on a label with a seriously broken tag like `label=<<test test>`, but that is during the parsing of the DOT file, not while the gvpr program is traversing it itself. Also, just as other Graphviz executables, it requires an entire DOT file as input, not just an HTML string. See attachments for examples: [is-node-html.gvpr](https://github.com/pydot/pydot/files/3665635/is-node-html.gvpr.txt), [is-node-html-1.dot](https://github.com/pydot/pydot/files/3665636/is-node-html-1.dot.txt), [is-node-html-2.dot](https://github.com/pydot/pydot/files/3665637/is-node-html-2.dot.txt).
  - No: In the Graphviz C libraries (even though pydot currently does not use those), I found the `aghtmlstr()` function, which according to the [cgraph manual page](https://graphviz.gitlab.io/_pages/pdf/cgraph.3.pdf) can be used to "query if a string is an ordinary string or an HTML-like string". However, after reading the source code and testing it a bit, I believe that, similar to the `gvpr` function `ishtml()`, the return value of `aghtmlstr()` just depends on if the string was claimed to be an HTML-like string at the moment it was added. There does not seem to be any actual XML or (DOT) HTML validation involved. The Graphviz C library example code mentioned above contains examples (`graphviz-html-test.c`).
  - Possibly: In the Graphviz source code, in [`lib/common`](https://gitlab.com/graphviz/graphviz/tree/master/lib/common) there are some files starting with `html*` that seem to do the validation and parsing. They use expat (C library for parsing XML) and Bison (a parser generator). Unfortunately, I could not immediately find a mention of them in the header files of the compiled Graphviz libraries, so they may not be part of the API. At first glance, `htmlparse.y` seems to be too much integrated with the parsing process for just validation, but `htmllex.c` could be a possible candidate, although there would clearly still be a long way to go then.

- The table below shows the combinations of Graphviz stdout/stderr/exit code that I have seen so far, sorted from most serious error to normal behavior. It is probably still incomplete.

 stderr          | exit code (0=success) | output on stdout? | example
-----------------|-----------------------|-------------------|-----------------------------
 error(+warning) | 1                     | no                | [Example 1](https://github.com/pydot/pydot/issues/215#issue-499470442) in my earlier comment.
 error(+warning) | 1                     | yes               | [Examples 2 and 3](https://github.com/pydot/pydot/issues/215#issue-499470442) in my earlier comment.
 warning only    | 0                     | yes               | An edge to a node:port, but the node not having that port. This example is not related to HTML strings or labels, though.
 nothing         | 0                     | yes               | Normal behavior in case of no problems.
