### ISSUE TITLE
cant pass PyDot objects via multiprocessing Pool.starmap()?

### ISSUE THREAD

**Issue by sandrotosi** [pydot/pydot#216]
Hello,
i have a process that does this:

* generate a few thousands graph, as PyDot objects (`pydot.Dot(graph_type='digraph', simplify=False)` specifically)
* parses edges and nodes to enhance some information (set URLs, and stuff like that)
* generate an SVG image for each graph

the SVG generation part is the slowest one, as it call `/usr/bin/dot` and it may take even some minutes for the most complex graphs.

so i had the brilliant (!) idea to investigate using multiprocessing `Pool` (so that i can limit of parallel processing going on), but i stumbled in some issues i cant really understand.

i wrote a simple function, that would the the parallel task:

```
     def write_svg_graph(graph, outfile):
        with open(outfile, 'wb') as f:
            f.write(graph.create(format='svg'))
```

stored my pairs of (PyDot, <path i want the file to be generated to>) in the `work` list and then setup mp as:

```
    with mp.Pool(mp.cpu_count()-2) as p:
        p.starmap(write_svg_graph, work)
```

and this where the problems start; running this code sequentially (so just call `write_svg_graph`) from within the same script works just fine, but with mp i get:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "myscript.py", line 146, in write_svg_graph
    f.write(graph.create(format='svg'))
  File "/usr/lib/python3/dist-packages/pydot.py", line 1882, in create
    prog = self.prog
AttributeError: 'Dot' object has no attribute 'prog'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "myscript.py", line 179, in <module>
    p.starmap(write_svg_graph, work)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'Dot' object has no attribute 'prog'
```

which makes no sense (to me). so i change the function to be:

```
    def write_svg_graph(graph, outfile):
        graph.set_prog('/usr/bin/dot')
        with open(outfile, 'wb') as f:
            f.write(graph.create(format='svg'))
```

(explicitly setting the `prog` property) but:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "myscript.py", line 146, in write_svg_graph
    f.write(graph.create(format='svg'))
  File "/usr/lib/python3/dist-packages/pydot.py", line 1898, in create
    for img in self.shape_files:
AttributeError: 'Dot' object has no attribute 'shape_files'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "myscript.py", line 179, in <module>
    p.starmap(write_svg_graph, work)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'Dot' object has no attribute 'shape_files'
```

another property missing! but if i check the type of the object received in `write_svg_file` it's a PyDot.

Does anyone know whta's going on an how to parallelize the generation of SVG from PyDot objects via multiprocessing? thanks! :)

**Comment by peternowee** [comment]
See my reply in pydot/pydot#217.

**Comment by lkk7** [comment]
Pickling has been fixed.
