### ISSUE TITLE
HTML tags

### ISSUE THREAD

**Issue by 2br-2b** [pydot/pydot#366]
This library has been very resilient to my testing; however, I found a way to bug it out:

```python
import pydot
graph = pydot.Dot(graph_type="graph")
graph.add_node(pydot.Node(label="<b>h<b>")) # adding a / into the frame doesn't fix anything
filepath = "test.png"
graph.write_png(filepath)
```

```
"dot" with args ['-Tpng', '/tmp/tmp8cm1e2th'] returned code: 1

stdout, stderr:
 b''
b"Error: /tmp/tmp8cm1e2th: syntax error in line 2 near '['\n"

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/foo/.venv/lib/python3.10/site-packages/pydot/core.py", line 1587, in new_method
    self.write(path, format=f, prog=prog, encoding=encoding)
  File "/home/foo/.venv/lib/python3.10/site-packages/pydot/core.py", line 1662, in write
    s = self.create(prog, format, encoding=encoding)
  File "/home/foo/.venv/lib/python3.10/site-packages/pydot/core.py", line 1786, in create
    process.returncode == 0
AssertionError: "dot" with args ['-Tpng', '/tmp/tmp8cm1e2th'] returned code: 1
```

```python
>>> graph.to_string()
'graph G {\n [label=<a>h<a>];\n}\n'
```

Related to #357

**Comment by 2br-2b** [comment]
The solution is that, per https://graphviz.org/doc/info/shapes.html#html, html code needs to be surrounded by <>s like so:
```
<<b>h</b>>
```

Or by quotes to make it literal:

```
"<b>h</b>"
```

Is this something the library should handle or that the user should handle? Just adding <>s around it would cause any broken html to throw an error (plus you'd need to strip the whitespace).

I think the specific error is caused because need_quotes uses this regex to check for html tags:
```python
id_re_html = re.compile("^<.*>$", re.S | re.UNICODE)
```

which matches the above text, causing the error. I don't know enough about regex to check this properly.

**Comment by 2br-2b** [comment]
To escape input, `html.escape(string).replace("\n", "<br/>").replace("\t", "    ")` is seems to work. (I'm sure there's a better way to do this, especially the manual replaces) Per the docs:

> All non-printing characters such as tabs or newlines are ignored

**Comment by lkk7** [comment]
Hi @2br-2b, that's a good question – https://github.com/pydot/pydot/pull/363 is currently fixing the quoting of attributes, so I'm tagging @ferdnyc because that's related.
I believe the current behaviour is expected – if the user is advanced enough to use HTML labels/names, then they know that's a feature of Graphviz. If they know that's a feature of Graphviz, then they also should know that it has to be enclosed by additional `<` and `>`. 
So, if there's no additional `<` and `>`, then it can be quoted. I'm just not sure if @ferdnyc's PR correctly handles that. I might have tested too quickly, but it looked like `label="<b>abc</b>` doesn't get quoted which results in the error.

Or I just messed something up as I have to answer quickly now – I'll come back later 💯

**Comment by ferdnyc** [comment]
@2br-2b @lkk7 

Indeed, in graphviz's language the pairing of `<` and `>` is just another form of quoting, one which triggers interpretation of the value contained within as an "HTML-like string". Unfortunately, as you discovered, regular expressions aren't a great way to detect/parse such strings, as at least a simplistic one like our `id_re_html` can't distinguish between `<<b>A correct HTML-like string</b>>` and `<b>An incorrectly-formatted one</b>`. (We can't make the regexp look for `<<.*>>`, because `<This is <i>also</i> a valid HTML-like string.>`

It is often the case that users may _mistakenly_ surround their values with `<` and `>` when they **don't** mean to invoke HTML-like behavior. I think that's what happened in PR #300, where the user suggests automatically labeling unnamed nodes as `<unnamed>`. They likely meant `"<unnamed>"`, as graphviz will render `<unnamed>` as simply "unnamed". Like I said, `<` and `>` are just a special pair of quotation marks, to graphviz.

I'm not sure how much smarter we could make the `id_re_html` regex without actually having to _parse_ the HTML **inside** the `<` `>` characters fully, which isn't a prospect I particularly relish.

The main problem is, if someone _does_ want to use HTML like `<b>value</b>`, we can't put it inside double quotes because it won't be parsed as HTML that way (It'll just show up as literally "&lt;b&gt;value&lt;/b&gt;"), and we can't arbitrarily enclose any HTML we see in our own set of `<` `>` outer quotes, because if they _do_ include the required outer quotes, adding another set (`<<<b>value</b>>>`) makes the string no longer valid.

**Comment by ferdnyc** [comment]
> Maybe a separate **explicit** way of adding an HTML-valued string. If it's not used, then quote everything. But that would break things for people who did it the old way and still expect it to be unquoted.

You're running into the _exact_ hurdle I face-planted on just last week, in #339, trying to reinvent the handling of port and compass arguements to `Edge` endpoints. I even wrote this entire docstring for the Edge constructor, before basically about-facing and deciding to abandon it:

```python
class Edge(Common):
"""A graph edge.

This class represents a graph's edge with all its attributes.

Edge(src, dst,
        _src_port="port",
        _src_compass="(nw | n | ne | e | se | s | sw | w | c | _ )",
        _dst_port="port",
        _dst_compass="(nw | n | ne | e | se | s | sw | w | c | _ )",
        attributes...)

Required arguments:
    src: source node, subgraph, cluster, or endpoint expression
    dst: destination node, subgraph, cluster, or endpoint expression

Optional keyword-only arguments:
    _src_port, _dst_port: A port to which the edge should be attached.
    _src_compass, _dst_compass: The attachment direction of the edge.
    attributes: name=value pairs which set the edge's attributes.

See the graphviz documentation for details on endpoint ports and
compass attachments.

`src` and `dst` can be specified as a `Node`, `Subgraph` or
`Cluster` object, or a string containing the name of such an object.
If none of the port or compass parameters are used, the string may
be an endpoint expression, although this usage is discouraged.

Endpoint expressions
~~~~~~~~~~~~~~~~~~~~

An endpoint expression is a colon-separated list of the form
`node_id[:port][:compass]`. This syntax introduces ambiguity that
may require additional quoting, especially when names contain colons.
The _*_port and _*_compass keyword parameters, or the corresponding
set_*_port / set_*_compass setter methods, should be preferred over
endpoint expression syntax.

This call:

    Edge('"1: Red":nw', '"2: Blue":se', ...)

Will create an edge that connects the northwest part of `"1: Red"`
to the southeast part of `"2: Blue"`. Without the additional
quoting, the parser will interpret ` Red` and ` Blue` as port names,
and `1` and `2` as the source and destination names for the edge.

Prefer this syntax, which unambiguously creates the same edge:

    Edge("1: Red", "2: Blue", _src_compass="nw", _dst_compass="se", ...)

DO NOT attempt to mix endpoint expressions and port/compass parameters
on the same edge. Setting any of the parameters completely disables
all endpoint expression parsing; source and destination string values
will be treated as names only.

As a special case, even when none of the port or compass parameters are
set on an Edge, it will disable endpoint expression parsing if the string
value for an endpoint exactly matches the name of a Node, Subgraph, or
Cluster in the same graph hierarchy as the Edge. This permits creating
simple Edges that connect names containing colons, without requiring
extra quoting to prevent the name being parsed as an expression.

This Edge will be interpreted correctly, no extra quoting is needed:

    graph.add_node(Node("1: Red"))
    graph.add_node(Node("2: Blue"))
    graph.add_edge(Edge("1: Red", "2: Blue"))

Attributes
~~~~~~~~~~

All attributes defined in the Graphviz dot language are supported,
as well as any custom attributes created by the user.

Standard attributes will have setter and getter methods, for example:

    edge_instance.set_label()
    edge_instance.get_fontname()

Custom attributes can be modified using the instance's get/set methods:

    edge_instance.set("my_custom_attr", "value")
    attr_value = edge_instance.get("another_custom_attr")

All attributes are stored in a dictionary at the `"attributes"` key
of the instance's `obj_dict`, which can also be accessed directly:

    edge_attributes = edge_instance.obj_dict['attributes']
    edge_label = edge_attributes.get("label")
    edge_attributes.update({"fontname": "new font name"})
"""
```

...The problem with my carefully-considered and lovingly explicated design there is, it's never going to work. There are a bunch of problems with it:

1. For starters, I had to make the attributes that define the port values `_src_port` and `_dst_port`, because a quick GitHub code search revealed that `src_port` and `dst_port` [are actually **very common** custom attributes for graphviz nodes](https://github.com/search?q=src_port++path%3A*.dot&type=Code&ref=advsearch&l=&l=). I think some network-graphing software uses them. So, right off the bat my choice of naming was less-than-ideal. But that drove home the point that co-opting _any_ attribute names to use as new non-attribute arguments runs a high risk of breaking a lot of existing code.
2. That aside, it turns out that graphviz **already has standard attributes** for defining edge endpoint ports: `headport` and `tailport`. So I was reinventing the wheel by defining new arguments that are redundant with existing attributes, and it would make more sense for people to use _those_ if they want to assign port values outside of the endpoint IDs.
3. But the biggest issue is, the `id[:port][:compass]` syntax is _convenient_ and _popular_ with users familiar with the graphviz language, so much so that pushing people away from using it feels unnatural and user-unfriendly no matter how good my reasons are. Plus, we still have to support that syntax _anyway_, since the parser needs to be able to consume it when reading any of the tens of thousands of lines of existing graphviz source that use it and will continue to use it.

So, that's the basic story of how #339 ended up stalling and will probably never get finished as-is, though I'm still hoping to get most of the other improvements submitted as their own PRs. (Particularly the "recognize when edges name existing IDs containing colons, and interpret them correctly instead of parsing them as port arguments" logic, which I still think could be a huge DWIM improvement for pydot.)

Beyond that, in order to better interpret endpoint strings I'd have to have _access_ to the list of valid port names defined in the graph. Which would involve parsing both all of the record-based node labels, _and_ all of the HTML-like labels in their entirety, in order to capture the port values.

**Comment by ferdnyc** [comment]
Coming back to the HTML-like strings... there is one thing that _might_ work:

If we encounter a string that's surrounded by `<` `>`, what if we were to _strip off_ those outer angle brackets, then check the string to see whether we hit a `>` before we hit another `<`? If we _do_, then the string isn't a properly-formed HTML-like string and we should add our own set of `<` `>` around the outside of it.

...I have to think on that some more, and see if there are any ways it could go wrong. But it feels like it _might_ be a workable approach.

**Comment by ferdnyc** [comment]
Oh, wait, duh, yes it DOES. Because that _is_ a valid string that we DON'T need to wrap ourselves. Got myself turned around backwards for a second, there.

**Comment by lkk7** [comment]
Hmm, could you give a step by step example? Like:
- `<<>>abc>` --> `<>>abc` --> we hit a `<` before `>`so it would appear to be correct, even though it isn't? Or should we check twice, starting both from front and the back? 

(I'm just not in the greatest mental capacity now 😄)

**Comment by ferdnyc** [comment]
Basically, it wouldn't help us determine whether _any **arbitrary** string_ is HTML-like, but it would let us make better quoting decisions about **correct** HTML-like strings that may or may not be properly `<`,`>` quoted already.

**Comment by lkk7** [comment]
Ahh, now I get it, thanks! Checking if we've broken the tags by stripping the outermost `<>` seems to be a simple way of checking if the outer `<>` should be added. Now it's simple when I see it, but the fact you came up with this trick is insane.

**Comment by ferdnyc** [comment]
I've also done some experimenting just now in the [Graphviz Visual Editor](http://magjac.com/graphviz-visual-editor/), and confirmed/determined:

* `<<<b>text</b>>>` is a parse error, as I mentioned earlier
* `<<b>some <> text</b>>` is also a parse error, and breaks the node

Also, while [the docs](https://graphviz.org/doc/info/shapes.html#html) contain lots of notes about how spaces are handled in both the source and the output:

> All non-printing characters such as tabs or newlines are ignored. Above, a string is any collection of printable characters, including spaces. For tables, outside of the body of a [`<TD>`](https://graphviz.org/doc/info/shapes.html#td) element, whitespace characters are ignored, including spaces; within a [`<TD>`](https://graphviz.org/doc/info/shapes.html#td) element, spaces are preserved but all other white space characters are discarded. N.B. For technical reasons, if a table is wrapped in a font element such as [`<FONT>`](https://graphviz.org/doc/info/shapes.html#font) or [`<B>`](https://graphviz.org/doc/info/shapes.html#b), any space immediately before or after this will cause a syntax error. For example, the label
> ```html
> < <U><TABLE><TR><TD>a</TD></TR></U>>
> ```
> is not legal. Removing either the space or the `<U>...</U>` will fix this.
> 
> As is obvious from the above description, the interpretation of white space characters is one place where HTML-like labels is very different from standard HTML. In HTML, any sequence of white space characters is collapsed to a single space, If the user does not want this to happen, the input must use non-breaking spaces `&nbsp;`. This makes sense in HTML, where text layout depends dynamically on the space available. In Graphviz, the layout is statically determined by the input, so it is reasonable to treat ordinary space characters as non-breaking. In addition, ignoring tabs and newlines allows the input text to be formatted for easier reading.

...The reality is even weirder and more confusing than that. For one thing, spacing in HTML-like strings seems to dpeend on the output engine, because this:
```dot
graph g {
  n [label=<Wow,<font color="blue">some</font>text>];
}
```
Run through `dot -Tsvg` becomes this:
![t](https://github.com/pydot/pydot/assets/538020/c5a947e5-9a69-471f-9730-b47d5117f72b)


But run through `dot -Tpng` gets you this:
![t](https://github.com/pydot/pydot/assets/538020/16161020-e4f7-4e98-bdf9-b096f878e99a)

...May have something to do with the font size mismatch, too, I suppose.

**Comment by ferdnyc** [comment]
(And on a tangentially-related note, the Graphviz Visual Editor appears to have a rendering bug I'm about to report, because **it** renders this:
```dot
graph g {
  n [label=<Wow, <font color="blue">some</font> text>];
}
```
as:
![image](https://github.com/pydot/pydot/assets/538020/234581cb-c368-4b51-bc2a-3db5372c59ae)

You have to insert a _second_ space before "text" to get it to show just the single one.)

**Comment by ferdnyc** [comment]
Thinking about this some more, it might not be impossible to detect labels with HTML in them even when they _don't_ match the `"^<.*>$"` regular expression, simply because Graphviz supports a _very_ limited set of HTML tags. "HTML-like strings" are nowhere near as complex as _actual_ HTML, and can perhaps be **detected** — though not parsed — without summoning Zalgo.

Something like this, as a first sketch:
```python
HTML_LIKE_OPEN_TAGS = "(FONT|I|B|U|O|SUB|SUP|S|TABLE)"
HTML_LIKE_SINGLE_TAGS = "BR"

html_like_re = re.compile(
    rf"(
       <\s*[/]?\s*({HTML_LIKE_TAGS})[^>]*>
      |<\s*({HTML_LIKE_SINGLE_TAGS})\s*[/]?\s*>
   )",
   re.IGNORECASE | re.MULTILINE | re.VERBOSE)
```

If we get a match on that, we've got a fairly high confidence that the string contains some graphviz HTML. (We don't even need to match the other possible tags, like `TR|TD|IMG|HR|VR`, because those are only valid inside a `<table>` so we're not going to see those unless we also see `<table>`.)

Actually, since glomming all the attributes from the open tag with `[^>]*` could come back to bite us _and_ create false positives if someone creates a long label containing "x value < table size blah blah blah... y value > 0" or whatever, maybe we should _only_ scan for closing tags — they can't have attributes, so it's a much lighter-weight expression. And except for `<BR>` (and `<HR>`, `<VR>`, and `<IMG ...>` which we're not even searching for), any open tag will always have a corresponding closing tag, in a valid HTML-like string.

If a string matches the RE but _doesn't_ start with `<` and end with `>`, we should always add them. If it starts/ends with one but the other side's is missing, we can either assume it's missing both sides (probably safe), or if we're being really paranoid use my "remove the `<` / `>` and see whether we broke open a tag" test.

**Comment by ferdnyc** [comment]
Huh. \#TIL that graphviz won't even accept `<BR>` in an HTML-like string ­— it _has to be_ `<BR/>`. It can't be `< BR/>` or `<BR/ >`, either — those are both errors.

It also won't accept `< table>`, `</ table>`, or `< /table>`.

So, the fact that it's _that_ picky works in our favor as well, and makes the scanning even easier.

We do have to watch out, tho, as it will accept `<table >`, `</table >`, or any other form with trailing whitespace of any kind, even:
```dot
graph G {
    n [label=<<table

      ><tr><td>hi</td></tr></table

     >>];
}
```
