### ISSUE TITLE
AttributeError: 'Subgraph' object has no attribute 'create_attribute_methods'

### ISSUE THREAD

**Issue by tetron** [pydot/pydot#386]
The 3.0.1 release appears to have a breaking change?  Our test suite started to fail despite no changes to this part of our code:

https://github.com/common-workflow-language/cwltool/actions/runs/9961307362/job/27522543903?pr=1779#step:8:147

```
The error was: 
Traceback (most recent call last):
  File "/home/runner/work/cwltool/cwltool/cwltool/main.py", line 1163, in main
    printdot(tool, loadingContext.loader.ctx, stdout)
  File "/home/runner/work/cwltool/cwltool/cwltool/cwlrdf.py", line 211, in printdot
    cwl_viewer: CWLViewer = CWLViewer(printrdf(wf, ctx, "n3"))
  File "/home/runner/work/cwltool/cwltool/cwltool/cwlviewer.py", line 26, in __init__
    self._set_input_edges()
  File "/home/runner/work/cwltool/cwltool/cwltool/cwlviewer.py", line 103, in _set_input_edges
    inputs_subgraph.create_attribute_methods(["style"])
AttributeError: 'Subgraph' object has no attribute 'create_attribute_methods'
```

**Comment by ferdnyc** [comment]
@tetron 

Ah, yes, the `Klass.create_attribute_methods()` method was removed, and replaced with an internal function `__generate_attribute_methods(Klass, attributes)` in 3.0.0, to perform static monkey-patching of the pydot classes immediately after creation (which is compatible with type checking and introspection) instead of post-instantiation (which is not), and to better reflect its status as the internal method it was always intended to be.

Apologies that the change was left out of the changelog.

**Comment by ferdnyc** [comment]
(Honestly I would've sworn that change was part of 2.0.0 as well, I guess it went in right _after_ the release.)

**Comment by lkk7** [comment]
Yes, essentially the problem is with the use of `create_attribute_methods()`, which was intended to be an internal function from the start. It got hidden, and your tests broke.
Of course, that's our fault. 

I believe the issue can be easily fixed on your side by removing these calls: 
```python
inputs_subgraph.create_attribute_methods(["style"])
```
Looks like nowhere in the code this generated attribute method is actually used.
Instead, explicit `inputs_subgraph.set("style", "dashed")` is used in the very next line.

I've created a PR with this simple change: https://github.com/common-workflow-language/cwltool/pull/2019/

**Comment by ferdnyc** [comment]
The change has been retroactively added to the ChangeLog as a breaking change in 3.0.0 (in #387), apologies for blind-siding you with that one.

**Comment by tetron** [comment]
I didn't write this particular bit of code so I don't know what the intention was for using `create_attribute_methods()` in the first place, so I appreciate the quick response.  Thanks!

**Comment by lkk7** [comment]
Fixed some time ago in https://github.com/common-workflow-language/cwltool/pull/2019.
